# -*- coding: utf-8 -*-
"""Multimodal_Fusion_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU94YSJpRj45YdKe15UXF5vkY8o3ZO_X
"""

!pip install opencv-python librosa joblib tensorflow moviepy
!pip install google-generativeai

import cv2
import librosa
import numpy as np
import joblib
import os

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

from moviepy.editor import VideoFileClip

import google.generativeai as genai

MODEL_PATH = "/content/drive/MyDrive/vibexathon/models"

video_model = load_model(os.path.join(MODEL_PATH, "deepfake_video_model.h5"))

audio_model = joblib.load(os.path.join(MODEL_PATH, "audio_deepfake_model (1).pkl"))

image_model = load_model(os.path.join(MODEL_PATH, "deepfake_model_image.h5"))

text_model = joblib.load(os.path.join(MODEL_PATH, "fake_text_model (1).pkl"))

tokenizer = joblib.load(os.path.join(MODEL_PATH, "fake_text_tokenizer.pkl"))

text_model = joblib.load(os.path.join(MODEL_PATH, "fake_text_model (1).pkl"))

print(type(text_model))

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

text_model.to(device)

genai.configure(api_key="AIzaSyBsbgKj8apwZhi-_U9jVMWkTA7Auohs09M")

gemini_model = genai.GenerativeModel("gemini-2.5-flash")

def extract_video_frames(video_path):

    cap = cv2.VideoCapture(video_path)

    frames = []
    count = 0

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        if count % 30 == 0:

            frame = cv2.resize(frame,(128,128))
            frame = frame/255.0

            frames.append(frame)

        count += 1

    cap.release()

    return frames

def detect_video(video_path):

    frames = extract_video_frames(video_path)

    if len(frames) == 0:
        return 0

    fake_count = 0

    for frame in frames:

        frame = np.expand_dims(frame,axis=0)

        prediction = video_model.predict(frame,verbose=0)[0][0]

        if prediction > 0.7:
            fake_count += 1

    probability = fake_count / len(frames)

    return probability

def extract_audio(video_path):

    clip = VideoFileClip(video_path)

    if clip.audio is None:
        return None

    audio_path = "temp_audio.wav"

    clip.audio.write_audiofile(audio_path)

    return audio_path

def extract_audio_features(file_path):

    audio, sr = librosa.load(file_path, sr=16000)

    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)

    return np.mean(mfcc.T, axis=0)

def detect_audio(audio_path):

    features = extract_audio_features(audio_path)

    features = features.reshape(1,-1)

    prediction = audio_model.predict(features)[0]

    return 1 if prediction == 1 else 0

def detect_image(image_path):

    img = cv2.imread(image_path)

    img = cv2.resize(img,(224,224))

    img = img/255.0

    img = np.expand_dims(img,axis=0)

    prediction = image_model.predict(img,verbose=0)[0][0]

    return prediction

def detect(video, image, text, audio=None):

    if audio:
        audio_score = detect_audio(audio)
    else:
        audio_file = extract_audio(video)
        audio_score = detect_audio(audio_file) if audio_file else 0

import torch

def detect_text(text):

    encoding = tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    input_ids = encoding["input_ids"]
    attention_mask = encoding["attention_mask"]

    with torch.no_grad():
        outputs = text_model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

    logits = outputs.logits
    probs = torch.softmax(logits, dim=1)

    fake_score = probs[0][1].item()

    return fake_score

def multimodal_fusion(video_score,audio_score,image_score,text_score):

    scores = [video_score,audio_score,image_score,text_score]

    final_score = sum(scores)/len(scores)

    if final_score > 0.6:
        result = "Fake"
    else:
        result = "Real"

    return result, final_score

def generate_explanation(video_score, audio_score, image_score, text_score, result):

    prompt = f"""
You are an AI system explaining the output of a multimodal deepfake detection system.

The system analyzed four different modalities:

Video deepfake probability: {video_score}
Audio deepfake probability: {audio_score}
Image deepfake probability: {image_score}
Text misinformation probability: {text_score}

Final classification: {result}

Provide a clear explanation in the following structure:

1. Video Analysis
Explain whether the video frames appear manipulated or authentic.

2. Audio Analysis
Explain whether the audio appears AI generated or natural human speech.

3. Image Analysis
Explain whether the image shows signs of deepfake or manipulation.

4. Text Analysis
Explain whether the text content appears misleading, fake news, or authentic.

5. Final Conclusion
Explain why the system classified the content as Real or Fake.

Keep the explanation simple and understandable for general users.
"""

    response = gemini_model.generate_content(prompt)

    return response.text

def run_multimodal_system(video_path, image_path, text_input):

    video_score = detect_video(video_path)

    audio_file = extract_audio(video_path)

    if audio_file:
        audio_score = detect_audio(audio_file)
    else:
        audio_score = 0

    image_score = detect_image(image_path)
    text_score = detect_text(text_input)

    result, confidence = multimodal_fusion(
        video_score, audio_score, image_score, text_score
    )

    explanation = generate_explanation(
        video_score, audio_score, image_score, text_score, result
    )

    confidence_score = round(confidence, 2)

    if confidence_score < 0.3:
        interpretation = "Low likelihood of manipulation"
    elif confidence_score < 0.6:
        interpretation = "Moderate likelihood of manipulation"
    else:
        interpretation = "High likelihood of manipulation"

    return f"""
Result: {result}
Confidence: {confidence_score}
Interpretation: {interpretation}

Explanation:
{explanation}
"""

!ls

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

run_multimodal_system(

"01__hugging_happy.mp4",

"realtest.jpeg",

"Breaking news: Modi is PM of india"

)